export const apiConfig = {
  baseUrl: process.env.NEXT_PUBLIC_API_URL || process.env.NEXT_PUBLIC_API_BASE_URL || "http://127.0.0.1:8000/api",
  timeout: 15000,
  headers: {
    "Content-Type": "application/json",
    Accept: "application/json",
  },
  endpoints: {
    auth: {
      login: "/auth/login",
      logout: "/auth/logout",
      me: "/auth/me",
      refreshToken: "/auth/refresh",
      forgotPassword: "/auth/forgot-password",
      resetPassword: "/auth/reset-password",
    },
    users: {
      list: "/users",
      detail: (id: string) => `/users/${id}`,
      create: "/users",
      update: (id: string) => `/users/${id}`,
      delete: (id: string) => `/users/${id}`,
      roles: (id: string) => `/users/${id}/roles`,
    },
    roles: {
      list: "/roles",
      detail: (id: string | number) => `/roles/${id}`,
      create: "/roles",
      update: (id: string | number) => `/roles/${id}`,
      delete: (id: string | number) => `/roles/${id}`,
      permissions: (id: string | number) => `/roles/${id}/permissions`,
      updatePermissions: (id: string | number) => `/role/updatepermissions/${id}`,
      assignPermission: "/role/assignpermission",
    },
    permissions: {
      list: "/permissions",
      create: "/permissions",
    },
    departments: {
      list: "/departments",
    },
    vendors: {
      list: "/vendors",
      detail: (id: string | number) => `/vendors/${id}`,
      create: "/vendors",
      update: (id: string | number) => `/vendors/${id}`,
      delete: (id: string | number) => `/vendors/${id}`,
    },
    fabricators: {
      list: "/fabricators",
      detail: (id: string | number) => `/fabricators/${id}`,
      create: "/fabricators",
      update: (id: string | number) => `/fabricators/${id}`,
      delete: (id: string | number) => `/fabricators/${id}`,
    },
    clients: {
      list: "/clients",
      detail: (id: string | number) => `/clients/${id}`,
      create: "/clients",
      update: (id: string | number) => `/clients/${id}`,
      delete: (id: string | number) => `/clients/${id}`,
    },
    clientLocations: {
      list: "/client-locations",
      detail: (id: string | number) => `/client-locations/${id}`,
      create: "/client-locations",
      update: (id: string | number) => `/client-locations/${id}`,
      delete: (id: string | number) => `/client-locations/${id}`,
    },
    companyDocuments: {
      list: "/company-documents",
      detail: (id: string | number) => `/company-documents/${id}`,
      create: "/company-documents",
      update: (id: string | number) => `/company-documents/${id}`,
      delete: (id: string | number) => `/company-documents/${id}`,
    },
    expenseCategories: {
      list: "/expense-categories",
      detail: (id: string | number) => `/expense-categories/${id}`,
      create: "/expense-categories",
      update: (id: string | number) => `/expense-categories/${id}`,
      delete: (id: string | number) => `/expense-categories/${id}`,
    },
    expenses: {
      list: "/expenses",
      detail: (id: string | number) => `/expenses/${id}`,
      create: "/expenses",
      update: (id: string | number) => `/expenses/${id}`,
      delete: (id: string | number) => `/expenses/${id}`,
      pay: (id: string | number) => `/expenses/${id}/pay`,
    },
    orders: {
      list: "/orders",
      detail: (id: string | number) => `/orders/${id}`,
      create: "/orders",
      update: (id: string | number) => `/orders/${id}`,
      delete: (id: string | number) => `/orders/${id}`,
    },
    leads: {
      list: "/leads",
      detail: (id: string | number) => `/leads/${id}`,
      create: "/leads",
      update: (id: string | number) => `/leads/${id}`,
      delete: (id: string | number) => `/leads/${id}`,
    },
    inventoryItems: {
      list: "/inventory-items",
      detail: (id: string | number) => `/inventory-items/${id}`,
      create: "/inventory-items",
      update: (id: string | number) => `/inventory-items/${id}`,
      delete: (id: string | number) => `/inventory-items/${id}`,
    },
    products: {
      list: "/products",
      detail: (id: string | number) => `/products/${id}`,
      create: "/products",
      update: (id: string | number) => `/products/${id}`,
      delete: (id: string | number) => `/products/${id}`,
    },
    machines: {
      list: "/machines",
      detail: (id: string | number) => `/machines/${id}`,
      create: "/machines",
      update: (id: string | number) => `/machines/${id}`,
      delete: (id: string | number) => `/machines/${id}`,
    },
  },
}
